Repository Hsinha11/Leetcode-solutions, pull requests merged in 2024-10, with the labels that each got.

#3 Update README.md
  README.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted

#4 Newnew
  README.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted

#7 Added the solution for the Binary Tree Cameras problem
  968-binary-tree-cameras/README.md
  968-binary-tree-cameras/binary-tree-cameras.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted

#8 Added the solution for minimum-element-after-replacement-with-digit-sum
  3300-minimum-element-after-replacement-with-digit-sum/README.md
  3300-minimum-element-after-replacement-with-digit-sum/minimum-element-after-replacement-with-digit-sum.py
Labels: good first issue, hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted

#9 188-best-time-to-buy-and-sell-stock-iv
  188-best-time-to-buy-and-sell-stock-iv/188-best-time-to-buy-and-sell-stock-iv.cpp
  188-best-time-to-buy-and-sell-stock-iv/README.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted

#14 410. Split Array Largest Sum
  410-split-array-largest-sum/README.md
  410-split-array-largest-sum/Split-array-largest-sum.cpp
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#15 Added Split array largest sum
  -410-split-array-largest-sum/-410-split-array-largest-sum.cpp
  -410-split-array-largest-sum/readme.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#17 131. Palindrome Partitioning
  131-Palindrome-Partitioning/README.md
  131-Palindrome-Partitioning/palindromeparitioning.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#20 44 -Wildcard-Matching And Updated the readme according to the need
  44-Wildcard-Matching/44-Wildcard-Matching.cpp
  44-Wildcard-Matching/Readme.md
  README.md
  Readme.md
Labels: good first issue, hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#27 202- Happy number
  202-happy-number/happy-number.py
  202-happy-number/readme.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#23 added optimal cpp code for problem 229-majority-element-ii
  229-majority-element-ii/majority-element-ii.cpp
Labels: good first issue, hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#29 49-Group-Anagrams Solution added
  49-group-anagrams/group-anagrams.py
Labels: good first issue, hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#24 Solved the Combination Sum Problem on Leetcode with Python
  -216-Combination-Sum-III/Approach1.py
  -216-Combination-Sum-III/Approach2.py
  -216-Combination-Sum-III/README.md
  -216-Combination-Sum-III/SubmissionAccept.png
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#34 2938. Separate Black and White Balls
  2938. Separate Black and White Balls/README.md
  2938. Separate Black and White Balls/solution.cpp
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#36 Added 2044. Count Number of Maximum Bitwise-OR Subsets
  2044-count-number-of-maximum-bitwise-OR-subsets/README.md
  2044-count-number-of-maximum-bitwise-OR-subsets/count_number_of_maximum_bitwise_OR_subsets.cpp
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest2024

#35 632. Smallest Range Covering Elements from K Lists
  632. Smallest Range Covering Elements from K Lists/README.md
  632. Smallest Range Covering Elements from K Lists/smallest-range-covering-elements-from-k-lists.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#38 1593. Split a String Into the Max Number of Unique Substrings.cpp
  LEETCODE PROBLEM- 1593/1593. Split a String Into the Max Number of Unique Substrings.cpp
Labels: good first issue, hacktober, hacktoberfest, hacktoberfest2024

#39 Added problem 1823: Finding winner of the circular game.
  1823-find-the-winner-of-circular-game/README.md
  1823-find-the-winner-of-circular-game/find-winner-of-circular-game.cpp
Labels: enhancement, hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#41 Solution added for 118-Pascal-triangle
  -118-Pascal's-triangle/pascals_triangle.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#42 678. Valid Parenthesis String Solution
  678-valid-parenthesis-string/README.md
  678-valid-parenthesis-string/valid-parenthesis-string.cpp
  678-valid-parenthesis-string/valid-parenthesis-string.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#45 Problem "641. Design circular deque"
  641-design-circular-deque/README.md
  641-design-circular-deque/design-circular-deque.cpp
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#44 1493. Longest Subarray of 1's After Deleting One Element
  1493. Longest Subarray of 1's After Deleting One Element/README.md
  1493. Longest Subarray of 1's After Deleting One Element/longest-subarray-of-1s-after-deleting-one -element.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#43 2530. Maximal Score After Applying K Operations
  2530. Maximal Score After Applying K Operations/README.md
  2530. Maximal Score After Applying K Operations/Solution.cpp
Labels: enhancement, hacktober-accepted, hacktober, hacktoberfest, hacktoberfest2024

#55 463- island parameter
  463-islandparameter.cpp
Labels: enhancement, hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#54 27 Remove Element
  27-Remove-Element/27-Remove-Element.cpp
  27-Remove-Element/Readme.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#52 6. ZigZag Conversion
  6.Zigzag-Conversion/readme.md
  6.Zigzag-Conversion/zigzag-conversion.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#59 31. Next Permutation
  31-Next-Permutation/ReadMe.md
  31-Next-Permutation/next-permutation.py
Labels: enhancement, hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#57 151 Reverse words in a string
  151-reverse-words-in-a-string/README.md
  151-reverse-words-in-a-string/reverse-words-in-a-string.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#66 Update best-time-to-buy-and-sell-stock-ii.py
  122-best-time-to-buy-and-sell-stock-ii/best-time-to-buy-and-sell-stock-ii.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#65 Update house-robber.py
  198-house-robber/house-robber.py
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#67 27 Remove Element
  27-Remove-Element.cpp
  Readme.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#69 Added solution to 0001-Two-Sum
  0001-Two-Sum/readme.md
  0001-Two-Sum/two-sum.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#72 80. Remove Duplicates from Sorted Array II
  80-remove-duplicates-from-sorted-array-ii/README.md
  80-remove-duplicates-from-sorted-array-ii/remove-duplicates-from-sorted-array-ii.py
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#82 7.Reverse a integer.
  reverse_integer.cpp
  reverse_integer2.cpp
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#85 46. Permutations
  46-Permutations/46-Permutations.py
  46-Permutations/README.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#89 single element in a sorted array
  540. Single Element in a Sorted Array/readme.md
  540. Single Element in a Sorted Array/single element in a sorted array.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2024

#92 9. Palindrome Number
  9.ispalindrome.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#87 Created 48-rotate-image.java
  48-rotate-image/48-rotate-image.java
  48-rotate-image/README.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#98 283.Move all zeros to end
  Move_all_zeros_to_end/README.md
  Move_all_zeros_to_end/moveAllZeorosToEnd.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#97 509. Fibonacci Number
  509. Fibonacci/509.fibonacci.cpp
  509. Fibonacci/readme-fibonacci.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#99 485. Max Consecutive Ones
  485. MaxconsecutiveOnes/485. maxconsecutiveones.cpp
  485. MaxconsecutiveOnes/readme-maxconsecutiveones.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#102 268.Find missing number in array
  find_missing_number/Find_missing_Number_In_array.cpp
  find_missing_number/readme.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#105 Create -575-Distribute_Candies,py
  -575-Distribute_Candies,py
Labels: hacktoberfest-accepted, hacktoberfest2024

#104 1752. Check if Array is Sorted and Rotated
  1752. Check if Array is Sorted and Rotated/1752. sortedarray.cpp
  1752. Check if Array is Sorted and Rotated/readme-sortedarray.md
Labels: hacktoberfest-accepted, hacktoberfest2024

#107 125.Valid palindrome-solved
  valid_palindrome/readme_validpalindrome.md
  valid_palindrome/valid_palindrome.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#108 Patch 6
  -2-Add_Two_Number/-2-Add_Two_Numbers.py
  -2-Add_Two_Number/Readme.md
  -541-Reverse_String/-541-Reverse_string-ii.py
  -541-Reverse_String/Readme.md
  -575-Distribute_Candies/-575-Distribute_Candies,py
  -575-Distribute_Candies/Readme.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#106 Create -7-Reverse_Integer.c
  -7-Reverse_Integer.c
Labels: hacktoberfest-accepted, hacktoberfest2024

#103 Create -242-Valid_Anagram.py
  -242-Valid_Anagram.py
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#110 Patch 7
  -242-Valid-Anagram/-242-Valid_Anagram.py
  -242-Valid-Anagram/Readme.md
  -7-Reverse-Integer/-7-Reverse_Integer.c
  -7-Reverse-Integer/Readme.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024
