Repository Hsinha11/Leetcode-solutions, pull requests merged in 2025-10, with the labels that each got.

#124 Building Boxes code leetcode
  1739-Building-Boxes/Building-Boxes.py
  1739-Building-Boxes/README.MD
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#127 Add solution for Leetcode Problem "3. Longest Substring Without Repeating Characters"
  3-Longest-Substring-Without-Repeating-Characters/README.md
  3-Longest-Substring-Without-Repeating-Characters/Solution.cpp
  3-Longest-Substring-Without-Repeating-Characters/Solution.java
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#126 Add Solution for LC:1906
  1906_Minimum_Absolute_Difference_Queries/1906_Minimum_Absolute_Difference_Queries.java
  1906_Minimum_Absolute_Difference_Queries/README.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#132 Add Python solution and approach for 123 Best Time to Buy and Sell Stock III
  1021-distribute-coins-in-binary-tree/README.md
  1021-distribute-coins-in-binary-tree/distribute-coins-in-binary-tree.py
  123-best-time-to-buy-and-sell-stock-iii/README.md
  123-best-time-to-buy-and-sell-stock-iii/best-time-to-buy-and-sell-stock-iii.py
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#133 Add Python solution for 1468 and document approach & complexity
  1468-check-if-n-and-its-double-exist/README.md
  1468-check-if-n-and-its-double-exist/check-if-n-and-its-double-exist.cpp
  1468-check-if-n-and-its-double-exist/check-if-n-and-its-double-exist.py
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#144 Maximum the minimum powered city
  2528-Maximize-the-Minimum-Powered-City/2528-Maximize-the-Minimum-Powered-City.py
  2528-Maximize-the-Minimum-Powered-City/README.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#138 Added Python Solution for trapping rain water II
  407_Trapping_Rain_Water_II/407.Trapping_Rain_Water_II.py
  407_Trapping_Rain_Water_II/README.md
Labels: hacktober-accepted, hacktober, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#141 Add solution for LeetCode 322 Coin Change in C++ and Java
  322_Coin_Change/322_Coin_Change.cpp
  322_Coin_Change/322_Coin_Change.java
  322_Coin_Change/README.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#147 Update Readme.md
  Readme.md
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2025

#150 Added Solution for "Cheapest Flights Within K Stops" (LeetCode #787)
  -787-Cheapest Flights Within K Stops/Code.cpp
  -787-Cheapest Flights Within K Stops/Code.java
  -787-Cheapest Flights Within K Stops/Code.py
  -787-Cheapest Flights Within K Stops/Readme.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#151 Update Readme.md
  Readme.md
Labels: hacktober-accepted, hacktoberfest2025

#157 Added N-Queens Problem Solution (LeetCode 51)
  -51-N_Queens/Code.cpp
  -51-N_Queens/Code.java
  -51-N_Queens/Code.py
  -51-N_Queens/Readme.md
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2025

#155 Add solution for Problem #1903: Largest Odd Number in String
  1903-largest-odd-number-in-string/README.md
  1903-largest-odd-number-in-string/largest-odd-number.cpp
Labels: hacktoberfest-accepted, hacktoberfest2025

#159 added 3703_remove_kBalance_substrings
  -3703-Remove_KBalanced_Substrings/-3703-Remove_KBalanced_Substrings.md
  -3703-Remove_KBalanced_Substrings/-3703-Remove_KBalanced_Substrings.py
Labels: hacktoberfest-accepted, hacktoberfest2025

#160 Add solution for LeetCode 217: Contains Duplicate (C++ with README)
  322_Coin_Change/217-contains-duplicate/README.md
  322_Coin_Change/217-contains-duplicate/contains-duplicate.cpp
Labels: hacktoberfest-accepted, hacktoberfest2025

#161 Add Solution for Problem#3005: Count Elements With Maximum Frequency
  3005-Count-Elements-With-Maximum-Frequency/Count-Elements-With-Maximum-Frequency.py
  3005-Count-Elements-With-Maximum-Frequency/Readme.md
Labels: hacktoberfest-accepted, hacktoberfest2025

#162 Add Python solution and README update for Longest Substring Without R…
  3-Longest-Substring-Without-Repeating-Characters/README.md
  3-Longest-Substring-Without-Repeating-Characters/longest-substring-without-repeating-characters.py
Labels: hacktoberfest-accepted, hacktoberfest2025

#163 added 04.median of sorted array using BS
  -4-Median-Of-Two-Sorted-Arrays/-4-median_of_two_sorted_arrays.cpp
  -4-Median-Of-Two-Sorted-Arrays/-4-median_of_two_sorted_arrays.md
  -543-Diameter-of-Binary-Tree/-543-Diameter-of-Binary-Tree.md
  -543-Diameter-of-Binary-Tree/-543-Diameter-of-Binary-Tree.py
  -572-subtree-of-another-tree/-572-subtree-of-another-tree.md
  -572-subtree-of-another-tree/-572-subtree-of-another-tree.py
Labels: hacktoberfest-accepted, hacktoberfest2025

#167 Added problem 303 - range sum query
  303-Range_Sum_Query/README.md
  303-Range_Sum_Query/Range_Sum_Query.py
Labels: hacktoberfest-accepted, hacktoberfest2025
